// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-8idJEtKgvgSFVu7wNCflhy2i6QucM0',
    appId: '1:571641470512:web:3a24cbbb7089011a3957f5',
    messagingSenderId: '571641470512',
    projectId: 'appfluter-19d13',
    authDomain: 'appfluter-19d13.firebaseapp.com',
    databaseURL: 'https://appfluter-19d13-default-rtdb.firebaseio.com',
    storageBucket: 'appfluter-19d13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlONulnxZ-kgl-mABbeM1c1zUR7V83pw',
    appId: '1:571641470512:android:6d0f1758e5eac3413957f5',
    messagingSenderId: '571641470512',
    projectId: 'appfluter-19d13',
    databaseURL: 'https://appfluter-19d13-default-rtdb.firebaseio.com',
    storageBucket: 'appfluter-19d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfhu9BAMsUoRtQmZKaCkWAtAUNAx5BP1s',
    appId: '1:571641470512:ios:71bc697fd7e877053957f5',
    messagingSenderId: '571641470512',
    projectId: 'appfluter-19d13',
    databaseURL: 'https://appfluter-19d13-default-rtdb.firebaseio.com',
    storageBucket: 'appfluter-19d13.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfhu9BAMsUoRtQmZKaCkWAtAUNAx5BP1s',
    appId: '1:571641470512:ios:71bc697fd7e877053957f5',
    messagingSenderId: '571641470512',
    projectId: 'appfluter-19d13',
    databaseURL: 'https://appfluter-19d13-default-rtdb.firebaseio.com',
    storageBucket: 'appfluter-19d13.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH-8idJEtKgvgSFVu7wNCflhy2i6QucM0',
    appId: '1:571641470512:web:8e61e9b7e116be073957f5',
    messagingSenderId: '571641470512',
    projectId: 'appfluter-19d13',
    authDomain: 'appfluter-19d13.firebaseapp.com',
    databaseURL: 'https://appfluter-19d13-default-rtdb.firebaseio.com',
    storageBucket: 'appfluter-19d13.firebasestorage.app',
  );
}
